version: "1"
services:
  cpr-app:
    image: umesh/cprapp
    container_name: cpr-app-container
    ports:
      - "3000:3000"
    volumes:
      - "//c/Users/UmeshMadathil/PROJECT/cpr-app:/app"
      - "/app/node_modules"
    stdin_open: true # Equivalent to -i
    tty: true # Equivalent to -t
    environment:
      CHOKIDAR_USEPOLLING: "true"